services:
  node_app:
    container_name: my_node_app
    image: my_node_app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 5s
      retries: 3

  test_runner:
    container_name: tests
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    depends_on:
      node_app:
        condition: service_healthy
    networks:
      - test-network
    environment:
      - APP_ENDPOINT=http://node_app:3000

networks:
  test-network:
